#include "rounds_data.hpp"

const RoundInfo sLevel1_Wave1[11] = {
	RoundInfo(ROUND_COMMAND_COOLDOWN, 1.6f),
	RoundInfo(ROUND_COMMAND_SPAWN_ENEMY, 0u),
	RoundInfo(ROUND_COMMAND_COOLDOWN, 1.6f),
	RoundInfo(ROUND_COMMAND_SPAWN_ENEMY, 0u),
	RoundInfo(ROUND_COMMAND_COOLDOWN, 1.5f),
	RoundInfo(ROUND_COMMAND_SPAWN_ENEMY, 0u),
	RoundInfo(ROUND_COMMAND_COOLDOWN, 1.f),
	RoundInfo(ROUND_COMMAND_SPAWN_ENEMY, 0u),
	RoundInfo(ROUND_COMMAND_COOLDOWN, 1.f),
	RoundInfo(ROUND_COMMAND_SPAWN_ENEMY, 0u),
	RoundInfo(ROUND_COMMAND_END, 100u),
};
